# Site Settings
baseurl: "/blog"
url : "https://akouao.github.io"

# Blog Settings
theme_settings :
  title :  Naturelle Growth
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/avatar.png
    username : naturelle growth
    description : Keeping track of lessons learned

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate]
bootstrap:
  assets: true
